# Generated by Django 4.1.1 on 2022-09-25 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('file_description', models.TextField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 9, 25, 13, 39, 7, 786711))),
                ('updated_time', models.DateTimeField(default=datetime.datetime(2022, 9, 25, 13, 39, 7, 786711))),
            ],
        ),
    ]
