# Generated by Django 4.1.1 on 2022-09-27 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 22, 59, 42, 611908)),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 22, 59, 42, 611908)),
        ),
    ]
