# Generated by Django 4.1.1 on 2022-09-27 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_alter_files_created_time_alter_files_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 23, 12, 44, 855093)),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 23, 12, 44, 855093)),
        ),
    ]
