# Generated by Django 4.1.1 on 2022-09-28 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_alter_files_created_time_alter_files_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 22, 54, 28, 378096)),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 22, 54, 28, 378096)),
        ),
    ]
