# Generated by Django 4.1.1 on 2022-09-29 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_alter_files_created_time_alter_files_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 23, 23, 19, 24640)),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 23, 23, 19, 24640)),
        ),
    ]
