# Generated by Django 4.1.1 on 2022-09-30 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_alter_files_created_time_alter_files_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_name',
            field=models.CharField(db_index=True, default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 14, 39, 14, 162325)),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 14, 39, 14, 162325)),
        ),
    ]
